sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t petarprlina/docker-react .
  
script:
  - docker run petarprlina/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2" # pise u URL-u
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-482783259395"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"